services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: bestplay_app
      POSTGRES_PASSWORD: bestplay_app
      POSTGRES_DB: bestplay_app_development
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
